### ISSUE TITLE
Animate alpha

### ISSUE THREAD

**Issue by bradws** [Temechon/bGUI#2]
Hi there,
I'm trying to 'fade-out' the GUIPanel 'boy' in the example by applying an animation to the Mesh.

I have modified the 'animate' function in 'index.js' to be:

```
BABYLON.Animation.CreateAndStartAnimation("", mesh, "material.alpha", 15, fps, 1.0, 0.0, BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT);
(note I'm modifying the alpha from 1.0 to 0.0)
```

... and the image DOES fade out, however as soon as the animation begins, a black rectangle appears 'behind?' the image, and slowly fades out with the image. What is this black rectangle, and how do i get rid of it? (viewed in Chrome and Firefox latest versions)

On another related matter, your Roadmap for v1.3 suggests putting in animation effects on GUIPanel (which is great!), but my question is that if we can get at the mesh (via the GUIPanel.Mesh property), can't we just use the standard Babylon animation features?

Cheers.

**Comment by Kimoen** [comment]
Hi Bradws, 

You can totally use panel.mesh and animate it the way you want.
The purpose of effects is to have pre-built animations, like flip or fade-in for example :)
I'll try to reproduce your bug and fix it if I can.

**Comment by Kimoen** [comment]
I added a fadein/fadeout animations for GUIObjects. it should be fixed now.

**Comment by bradws** [comment]
Thanks Temechon,

I was playing around with the demo.
I wanted to animate the `boy.mesh.material.alpha` property. It did animate, but a strange black rectangle would fade in/out with the bounding rectangle of the GUIPanel. I eventually worked it out; I had to set the material's useAlphaFromDiffuseTexture: `boy.mesh.material.useAlphaFromDiffuseTexture = true;`

This black rectangle is now no-more!

FYI, I was using the following code:

```
var boy = new bGUI.GUIPanel("boy", assets["bigboy"], assets["bigboyred"], gui);
boy.relativePosition(new BABYLON.Vector3(0.85,0.5,0));

//  Allow the alpha-animation to work
boy.mesh.material.useAlphaFromDiffuseTexture = true; 
```

..and then on click of the vault button, I call the function to animate it:

```
vault.onClick = function() {
    animateTest(boy.mesh, 60);
};
```

...

```
function animateTest (mesh, fps) {

    BABYLON.Animation.CreateAndStartAnimation("", mesh, "material.alpha", 30, 15, 0.0, 1.0, BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT);
}
```

Cheers,
bws.
