### ISSUE TITLE
Mesh trigger OnPointerOverTrigger not working?

### ISSUE THREAD

**Issue by bradws** [Temechon/bGUI#4]
Hi Temechon,

I was looking at making a GUIPanel do something when a mouse rolls over it. I notice u use an `onClick` function:

```
var vault = new bGUI.GUIPanel("boy", assets["vault11"], null, gui);
vault.relativePosition(new BABYLON.Vector3(0.5,0.85,0));
vault.onClick = function() {
                animateTest(boy.mesh, 60);    // boy = new bGUI.GUIPanel(...)
};
```

This is great, however I thought I could get at the `mesh` property and use the `ActionManager` and have the triggers `OnPointerOverTrigger` and `OnPointerOutTrigger` and all that wonderful Babylon stuff at:
http://doc.babylonjs.com/tutorials/How_to_use_Actions

I tried a simple example with a normal Mesh using Babylon and the `OnPointerOverTrigger` worked.
I tried a simple example with the Mesh from GUIPanel and the `OnPointerOverTrigger` didn't seem to trigger.

Is the `OnPointerOverTrigger` and `OnPointerOutTrigger` supported? Will there be an `onPointerOver` and `onPointerOut` event?

Thanks again,
bws.

**Comment by Kimoen** [comment]
I'll add it to my roadmap.

**Comment by Kimoen** [comment]
You have now two more methods on GUIObjects : onHoverOn and onHoverOut, that are activated by guiSystem.enableClick(). You can use them like onClick (example are in the first demo)

**Comment by bradws** [comment]
That's great. It works perfectly, thanks!
bws.
