### ISSUE TITLE
Possible bug in Mesh scaling?

### ISSUE THREAD

**Issue by bradws** [Temechon/bGUI#5]
Hi there,

There may possibly be a bug in the mesh scaling in bGUI as I seem to be having an issue with the GUIPanel/GUIText.

In a normal Babylon mesh, I can do scaling like:
`myMesh.scaling = new BABYLON.Vector3( 2, 2, 2 );       // will double the size of the mesh`

...but in a GUIPanel, when I do:
`myGUIPanel.mesh.scaling = new BABYLON.Vector3( 2, 2, 2 );`
nothing seems to appear.

I notice when I go:
`myGUIPanel.mesh.scaling = new BABYLON.Vector3( 100, 100, 100 );`
it does appear (albeit smaller), and when I do:
`myGUIPanel.mesh.scaling = new BABYLON.Vector3( 200, 200, 200 );`
it is even bigger.

Is this a bug and can it be looked into, or is there another way to do it for the GUIPanel/GUIText ?

Thanks muchly again,
bws.

**Comment by Kimoen** [comment]
Hello, 

bGUI update the scaling of the mesh, to adapt the panel to the given texture. You have to use this if you want to scale your panel: 

```
panel.mesh.scaling.scaleInPlace(2); // Will scale by 2 the panel
```
